### ISSUE TITLE
postedAt and createdAt not populating in filenames

### ISSUE THREAD

**Issue by Smalfinn** [sim0n00ps/OF-DL#467]
Relevant part of config.json:
`  "PaidPostFileNameFormat": "{postedAt}_{filename}",`
`  "PostFileNameFormat": "{postedAt}_{filename}",`
`  "PaidMessageFileNameFormat": "{createdAt}_{filename}",`
`  "MessageFileNameFormat": "{createdAt}_{filename}",`
`  "RenameExistingFilesWhenCustomFormatIsSelected": true,`

With this config my filenames only have the {filename} populated with no dates.

**Comment by FarmingCrops** [comment]
"PaidPostFileNameFormat": "",
  "PostFileNameFormat": "{mediacreatedAt} {filename}",
  "PaidMessageFileNameFormat": "{mediaCreatedAt} {filename}",
  "MessageFileNameFormat": "{mediaCreatedAt} {filename}",
  "RenameExistingFilesWhenCustomFormatIsSelected": true,

**Comment by melithine** [comment]
Are you still experiencing this under 1.7.75?

**Comment by FarmingCrops** [comment]
no they are not working for some reason

**Comment by FarmingCrops** [comment]
i fixed my problem 

https://sim0n00ps.github.io/OF-DL/docs/config/custom-filename-formats/#examples

mediaCreatedAt
{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": true,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "{mediaCreatedAt} {filename}",
  "PostFileNameFormat": "{mediaCreatedAt} {filename}",
  "PaidMessageFileNameFormat": "{mediaCreatedAt} {filename}",
  "MessageFileNameFormat": "{mediaCreatedAt} {filename}",
  "RenameExistingFilesWhenCustomFormatIsSelected": true,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 0,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "before",
  "CustomDate": null,
  "ShowScrapeSize": true,
  "DownloadPostsIncrementally": false,
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
  "FFmpegPath": "C:/ffmpeg.exe",
  "BypassContentForCreatorsWhoNoLongerExist": false,
  "CreatorConfigs": {},
  "DownloadDuplicatedMedia": false,
  "IgnoredUsersListName": "",
  "LoggingLevel": "Error"
}

postedAt

{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": true,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "{postedAt} {filename}",
  "PostFileNameFormat": "{postedAt} {filename}",
  "PaidMessageFileNameFormat": "{createdAt} {filename}",
  "MessageFileNameFormat": "{createdAt t} {filename}",
  "RenameExistingFilesWhenCustomFormatIsSelected": true,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 0,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "before",
  "CustomDate": null,
  "ShowScrapeSize": true,
  "DownloadPostsIncrementally": false,
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
  "FFmpegPath": "C:/ffmpeg.exe",
  "BypassContentForCreatorsWhoNoLongerExist": false,
  "CreatorConfigs": {},
  "DownloadDuplicatedMedia": false,
  "IgnoredUsersListName": "",
  "LoggingLevel": "Error"
}

**Comment by Smalfinn** [comment]
Hello, apologies on my late reply.

This is still broken on 1.7.83 using these options:
  "PaidPostFileNameFormat": "{mediaCreatedAt}_{fielname}",
  "PostFileNameFormat": "{mediaCreatedAt}_{fielname}",
  "PaidMessageFileNameFormat": "{mediaCreatedAt}_{fielname}",
  "MessageFileNameFormat": "{mediaCreatedAt}_{fielname}",

**Comment by melithine** [comment]
This is my config, which works:
```
  "PaidPostFileNameFormat": "{username} - PPV Post - {mediaCreatedAt}_{id}_{mediaid}",
  "PostFileNameFormat": "{username} - Post - {mediaCreatedAt}_{id}_{mediaid}",
  "PaidMessageFileNameFormat": "{username} - PPV Message - {mediaCreatedAt}_{id}_{mediaid}",
  "MessageFileNameFormat": "{username} - Message - {mediaCreatedAt}_{id}_{mediaid}",
```

**Comment by Smalfinn** [comment]
Using your config, I still get the same error of the files just being called their filenames.

It is only effecting the Paid posts/messages.

Looking at the logs the "created" property is "null" for my paid posts so maybe a onlyfans issue?

**Comment by melithine** [comment]
Not sure, we'd need a debug log to see what's going on there.
