### ISSUE TITLE
(Unexpected) Auth Issues

### ISSUE THREAD

**Issue by pervinha-debug** [sim0n00ps/OF-DL#701]
Recently, I've moved the OFDL folder to a new HDD and It has started to present login problems. I've managed to solve auth issues on previous browser updates. But this time, it's been impossible. I've already used the browser extension to gurantee that data is correct, but I'm still failing :/....
And yeah, I've corrected the ffmpeg path.

I'd be profundly grateful for any help,

Best Regards

![Image](https://github.com/user-attachments/assets/2779e86d-0c19-45be-9ae5-515a77ee4685)

**Comment by sim0n00ps** [comment]
Are you running the code locally?

**Comment by hydr0homiee** [comment]
I get the same message without being in debug mode. I've triple checked all my `auth.json` values and am still getting this error when I launch the OFDL.exe

![Image](https://github.com/user-attachments/assets/8f88533e-f3b1-4aa1-9e33-a647ea67feda)

**Comment by deadbeatdandylyon** [comment]
I am a normal user

I currently am using the web browser Microsoft Edge for my scrapes and have successfully been able to scrape multiple accounts, as a test maybe you can try your auth.json information from another web browser then the one your currently using? Also if your using a VPN can try to disable that as a test - I'm not currently using a VPN reason for my suggestion.

**Comment by sim0n00ps** [comment]
> I had the same problem
> 
> ![Image](https://github.com/user-attachments/assets/b7dcee48-e40a-4eb4-bafe-32637ca50eee)
> 
> USER_AGENT section of auth.json file Original Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0 Modified Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0
> 
> Produces an error screen like the one below
> 
> ![Image](https://github.com/user-attachments/assets/4330a1ce-2263-4ad5-abb8-a09bc0552ef3)

You need to update to V1.8.1, that should fix that error

**Comment by Wingzer01** [comment]
> > 나는 같은 문제가 있었다
> > ![Image](https://github.com/user-attachments/assets/b7dcee48-e40a-4eb4-bafe-32637ca50eee)
> > auth.json 파일의 USER_AGENT 섹션 원래 크롬 / 132.0.0.0 사파리 / 537.36 에지 / 132.0.0.0 수정 된 크롬 / 133.0.0.0 사파리 / 537.36 에지 / 133.0.0.0
> > 아래와 같은 오류 화면을 생성합니다.
> > ![Image](https://github.com/user-attachments/assets/4330a1ce-2263-4ad5-abb8-a09bc0552ef3)
> 
> V1.8.1로 업데이트해야 해당 오류가 수정됩니다.

thank you

**Comment by hookd85** [comment]
I've updated to 1.8.1 and still getting the auth error, I've downloaded the auth.json using the browser extension and _still_ getting the same error.

**Comment by hydr0homiee** [comment]
Updating to 1.8.1 fixed it, thanks!

**Comment by pervinha-debug** [comment]
> Are you running the code locally?

Yes. I'm gonna try to update my script to the new version.

**Comment by pervinha-debug** [comment]
I've downloaded a newer version and it works fine. But for some reason the menu does not appear and it goes straight to downloading everything. Is there a config to enable the interactive prompt?
