### ISSUE TITLE
Trouble login after update

### ISSUE THREAD

**Issue by xanda971** [sim0n00ps/OF-DL#741]
<img width="1171" alt="Image" src="https://github.com/user-attachments/assets/988b85ce-2a58-4be3-8b0e-b98e5c4b9be5" />

anyone know what's wrong???

**Comment by melithine** [comment]
Upgrade to 1.8.1, that error was already addressed.

**Comment by xanda971** [comment]
I've download  and unzip the latest 1.8.1 OFDL1.8.1.zip package tho, terminal still showed that I should upgraded to 1.8.1.
but the previous update terminal showed same message ,it worked fine still.

**Comment by xanda971** [comment]
Thanks a lot ! OF-DL works functionally now.

**Comment by xanda971** [comment]
Thanks a lot! Updated seems works for this issue! Do I also have to update ffmpeg also? because right now when I run OF-DL it showed that :
"The provided path does not exist or is not accessible.
Cannot locate FFmpeg; please modify config.json with the correct path."
but I literally copy and paste the right path into the config.json. 
can't see where it go wrong

**Comment by melithine** [comment]
For Docker, just leave that blank or point it at `/usr/bin/ffmpeg`.

**Comment by xanda971** [comment]
Thanks for your patience and help!!! It's totally funtional now!

**Comment by melithine** [comment]
Happy to help!
