### ISSUE TITLE
Exception caught: SQLite Error 1

### ISSUE THREAD

**Issue by returnofthelivinged** [sim0n00ps/OF-DL#766]
After updating to 1.9.2 I started getting this error when downloading (Files still download)

2025-03-25 00:25:41.563 -04:00 [ERR] Exception caught: SQLite Error 1: 'table medias has 14 columns but 13 values were supplied'.

StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at OF_DL.Helpers.DBHelper.CreateDB(String folder)
2025-03-25 00:25:43.439 -04:00 [ERR] Exception caught: SQLite Error 1: 'Cannot add a column with non-constant default'.

StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at OF_DL.Helpers.DBHelper.EnsureCreatedAtColumnExists(SqliteConnection connection, String tableName)
   at OF_DL.Helpers.DBHelper.AddPost(String folder, Int64 post_id, String message_text, String price, Boolean is_paid, Boolean is_archived, DateTime created_at)
2025-03-25 00:25:44.957 -04:00 [ERR] Exception caught: SQLite Error 1: 'Cannot add a column with non-constant default'.

StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at OF_DL.Helpers.DBHelper.EnsureCreatedAtColumnExists(SqliteConnection connection, String tableName)
   at OF_DL.Helpers.DBHelper.AddMessage(String folder, Int64 post_id, String message_text, String price, Boolean is_paid, Boolean is_archived, DateTime created_at, Int32 user_id)

**Comment by pakkalin** [comment]
same issue here

**Comment by ViRGEdx** [comment]
Yep, I'm seeing this as well. It looks like it's due to the new "current date timestamp" column in the SQL media table that was added by https://github.com/sim0n00ps/OF-DL/issues/740

From what I can tell, the update isn't reformatting the table to add the column when upgrading from an older version of OF-DL. As a result, the SQL media tables don't get updated, and OF-DL essentially loses the ability to make records of downloading any new media. Deleting the `user_data.db` files will fix the issue, but it means losing all records of past downloads.

**Comment by sim0n00ps** [comment]
Thanks for this, didn't see this during testing and thought I had accounted for this. I will try and fix later on.

**Comment by sim0n00ps** [comment]
Fixed in 1.9.3

**Comment by giggawat** [comment]
Hi, I’m still having this issue even after updating. I copied over the auth and cdm. Could that have anything to do with it?
