### ISSUE TITLE
Shutting down immediately after open!

### ISSUE THREAD

**Issue by sasssy2019** [sim0n00ps/OF-DL#86]
It was working great, but I opened it today for the first time this week and it opens, logs in successfully, then closes immediately. How do I fix this?

**Comment by sim0n00ps** [comment]
What version are you running? If you can screen record what happens so I can see the exception

**Comment by sasssy2019** [comment]
I apologize, I wasn't familiar with this site and didn't know there was a section for closed issues, so after opening mine, I saw the closed and noticed this issue already addressed. It is working now with the new version you put out there. Thanks!

However, I do have a new question.. is there a way to just download the files per date or date range and not have it try to redownload all the videos again? I know that it does not redownload them if it has already downloaded it once and the folder is still there, but what if I only want 1 specific dated video to download?

**Comment by sasssy2019** [comment]
Nevermind, found an issue. It logs on successfully and gives me the options for select all, lists, custom, edit auth.json and exit. I select list like I normally do, but then it crashes and closes out immediately. How do I fix that?

**Comment by sim0n00ps** [comment]
> Nevermind, found an issue. It logs on successfully and gives me the options for select all, lists, custom, edit auth.json and exit. I select list like I normally do, but then it crashes and closes out immediately. How do I fix that?

Screen record what happens and try to see what the exception is

**Comment by sim0n00ps** [comment]
I thought I fixed this but clearly I haven't, extract that and put the dll file in the same directory as OF DL.exe and see if that has any difference
[Spectre.Console.zip](https://github.com/sim0n00ps/OF-DL/files/12050838/Spectre.Console.zip)

**Comment by sasssy2019** [comment]
Same issue. Still crashes when selecting List. I added the dll to where the OF DL application is and still crashing.

**Comment by sim0n00ps** [comment]
Fuck sake, okay I'll revert back to using the orginal package from nuget and create a new release

**Comment by sasssy2019** [comment]
Okay, please let me know once the new release is out. Thanks.

**Comment by sim0n00ps** [comment]
Its out https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.21

**Comment by sasssy2019** [comment]
Unfortunately, same thing is happening. I updated to the latest and it still crashes when selecting list. I can select everything else and it does not crash, just the list selection. 

https://github.com/sim0n00ps/OF-DL/assets/139555218/1ebdfd46-b5fa-4db7-be0c-4e73ac5fcc09

**Comment by sim0n00ps** [comment]
> Unfortunately, same thing is happening. I updated to the latest and it still crashes when selecting list. I can select everything else and it does not crash, just the list selection. 
> 
> https://github.com/sim0n00ps/OF-DL/assets/139555218/1ebdfd46-b5fa-4db7-be0c-4e73ac5fcc09
> 
> 

So it only happens when choosing List? And when you select Custom does it actually download stuff after you select some users?

**Comment by sasssy2019** [comment]
Yes, only happens when choosing List. When choosing custom, it looks like only the free accounts I subscribe to are listed, and none of the paid subscriptions are there. When I choose an account on Custom, it does download their post etc. Also when I choose Select All it starts downloading all from A-Z, which is correct. So only the List selection is crashing. Also, just a note, it use to take like 30 secs for the selections to come up after successfully logging in, but now it takes like 3 min. Not a big deal, but just letting you know.

**Comment by sim0n00ps** [comment]
Yeah I haven't got any idea what's going on so unfortunately I can't really help you anymore

**Comment by sasssy2019** [comment]
Okay, I will delete it all and start again and see if that work with the latest update. Can you answer the question that I asked previously about the downloading only in a date range?

**Comment by sim0n00ps** [comment]
> Okay, I will delete it all and start again and see if that work with the latest update. Can you answer the question that I asked previously about the downloading only in a date range?

It can be done but I think it will be a massive pain to implement with what I currently have so not something I'll be considering atm

**Comment by sasssy2019** [comment]
Hi again, I believe I got it to work but now I am having issues with adding the new keys and the steps with dumping your own l3 cdm in order to view the drm videos. I get stuck at opening the phone and receive the error below when booting it.

![image](https://github.com/sim0n00ps/OF-DL/assets/139555218/75d38fa3-7402-422a-8301-bcd0eeab12fb)

**Comment by Lciron** [comment]
Same problem here, I'm on the latest version and the program just closes after opening instantly, any solution?

**Comment by sasssy2019** [comment]
> Same problem here, I'm on the latest version and the program just closes after opening instantly, any solution?

I just updated to the latest one and it didn't close instantly after opening.
